[book]
title = "Ã‰tale"
authors = ["Julius Zhang"]
language = "en"
src = "book/src"

[build]
build-dir = "book/build"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/juliuszhang/etale"
edit-url-template = "https://github.com/juliuszhang/etale/edit/main/{path}"

[output.html.search]
enable = true

